ログイン・ログアウト機能の実装
masaya09/TwitterCloneApp pull request #2
Opened 2021-07-20 08:27 UTC by masaya09

ログイン・ログアウト機能を実装しました。問題がないか確認お願いします。

2021-07-22 14:43 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-07-22 14:43 UTC, Akinori13 commented on mysite/settings.py
> +    'crispy_forms',
`django-crispy-forms`を`requirements.txt`に追記してください。

2021-07-22 14:43 UTC, Akinori13 commented on mysite/settings.py
> +)
①今、プロジェクト共通の静的コンテンツは、`static`フォルダに配置されていると思います。
②Djangoは、本番環境では、セキュリティやパフォーマンスの観点から、`python manage.py collectstatic`を実行して、静的コンテンツを`STATIC_ROOT`で指定された一つのフォルダにまとめることを推奨しています。今、`.gitignore`を読む限り、本番サーバーにおいては、`static`フォルダに静的コンテンツを配置すると思います。

現在のコードでは、STATIC_ROOT`で指定されたフォルダとプロジェクト共通の静的コンテンツが配置されるフォルダが被っています。したがって、プロジェクト共通の静的コンテンツを配置するフォルダを変更してください。

2021-07-22 15:17 UTC, masaya09 commented on mysite/settings.py
> +)
フォルダ名を変更すれば大丈夫ですか？

2021-07-23 08:17 UTC, Akinori13 requested changes
コメントしました。

2021-07-23 08:17 UTC, Akinori13 commented on templates/base.html
> +      <a class="nav-item nav-link" href="{% url 'tweet:topview' %}">Top</a>
```suggestion
      <a class="navbar-brand" href="{% url 'tweet:topview' %}">Top</a>
```
公式としてはこちらの書き方が掲載されています。

2021-07-23 08:17 UTC, Akinori13 commented on accounts/tests.py
> +class loginTests(TestCase):
```suggestion
class LoginTests(TestCase):
```

2021-07-23 08:17 UTC, Akinori13 commented on accounts/tests.py
> +        url = reverse('accounts:login')
`url`はクラス内で一つにまとめてしまってもよいです。あるいは、そもそも変数に入れなくてもよいです。

2021-07-23 08:40 UTC, masaya09 commented on accounts/views.py
> +            return redirect('accounts:login')
きちんと登録されているか確認する為だったんですが、navbar表示でloginしていない時signupとloginが表示されることを考えたら、紛らわしくなることに気づいたのでtweet:topviewの方に戻しました。

2021-07-25 12:42 UTC, Akinori13 requested changes
テストについて２点コメントしました。

2021-07-25 12:42 UTC, Akinori13 commented on accounts/tests.py
> +class LogoutTest(TestCase):
データベースはTestCaseごとに初期化されるので、この時点では`login_user`は登録されていません。
GET先は`accounts:logout`です。ログアウトできているかまで確認してください。

2021-07-25 12:42 UTC, Akinori13 commented on accounts/tests.py
> +class LoginTests(TestCase):
ログインに失敗することを確認するテストするコードも書いてください。

2021-08-01 09:05 UTC, Akinori13 approved these changes

2021-08-01 09:06 UTC, Akinori13 commented
LGTM!

2021-08-04 07:33 UTC, fumiharun11 commented on accounts/tests.py
> +        # 'accounts:login'にリダイレクトされることを確認
`accounts:login`へのリダイレクトで合っているか確認お願いします。コードとコメントに乖離があるように見えるので。

2021-08-04 07:33 UTC, fumiharun11 commented on accounts/tests.py
> +        self.client.logout()
responseを受け取った後にclientをlogoutしている意図はありますか？
ログアウトの状態になっていることをテストする方が自然な気がしています。

2021-08-04 08:47 UTC, masaya09 commented on accounts/tests.py
> +        # 'accounts:login'にリダイレクトされることを確認
直し忘れてました。
'accounts:login'から`tweet:topview`に変えました。

2021-08-04 09:35 UTC, fumiharun11 commented on accounts/tests.py
> +        self.assertEqual(response.status_code, 302)
これはステータスコードが302であるかどうかのテストですね。
厳密にログアウト状態にあるかは以下のテストで確認できるので調べてみてください。
```py
self.assertNotIn(SESSION_KEY, self.client.session)
```

2021-08-04 09:35 UTC, fumiharun11 commented on accounts/tests.py
> +        self.client.logout()
`accounts:logout`に対応するViewへログイン状態でGETリクエストを送信しているので、そのresponseを受け取る時には`self.client`はログアウト状態になっていると思います。
その上で、`self.client.logout()`で意図的にログアウトさせていますが、この処理に意味はありますか？
```py
response = self.client.get(reverse('accounts:logout'))
```

2021-08-04 10:14 UTC, fumiharun11 approved these changes
LGTM
![](https://media.giphy.com/media/QyrysGo7Hz70I/giphy.gif)

2021-08-04 10:15 UTC, merged