#ツイート機能の実装
masaya09/TwitterCloneApp pull request #3
Opened 2021-08-10 07:19 UTC by masaya09

ツイート機能を実装しました。
問題がないか確認をお願いします。

2021-08-12 13:03 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-08-13 05:48 UTC, Akinori13 requested changes
いくつかコメントしました。また前回コメントした場所で修正できていない部分も修正お願いします。

2021-08-13 05:48 UTC, Akinori13 commented on tweet/tests.py
> +        self.assertRaisesMessage(response, 'ツイートが失敗しました')
`print(Post.objects.all())`を用いると分かりますが、ツイートは成功しています。
重要なポイントは、PostCreateViewにおいてDjangoはPOSTのデータにある`author`は、PostCreateFormでfieldsに指定していないので、無視するということです。
PostCreateViewを見る限り、なりすましのテストは必要ありません。空白であった場合か140字以上である場合をテストしましょう。
なぜ`assertRaisesMessage`が適切な引数ではないのにエラーが生じていないのかは現時点では分かりかねますが、`assertRaisesMessage`の一般的な使い方ではないと思われますので、エラーメッセージを確認する他の方法を用いてください。

2021-08-13 05:48 UTC, Akinori13 commented on tweet/tests.py
> +    def test_with_postlist_get(self):
テストを実行するとエラーが生じます。

2021-08-13 05:48 UTC, Akinori13 commented on tweet/tests.py
> +    def test_with_fail_update_post(self):
- createと同様に`author`の意味はありませんから消しちゃってください。
- `self.assertRaisesMessage`は別のものにしてください。

2021-08-13 05:48 UTC, Akinori13 commented on tweet/tests.py
> +class PostUpdateViewTests(TestCase):
- 他に空白の場合か140字以上の場合のテストも追加してください。
- なりすましのテストはGet時とPost時があります。前者はエラーメッセージが表示されると思われます。後者は403になります。

2021-08-13 05:48 UTC, Akinori13 commented on tweet/tests.py
> +class PostDeleteViewTests(TestCase):
PostUpdateViewTestsと同様に修正してください。

2021-08-13 15:07 UTC, masaya09 commented on tweet/tests.py
> +    def test_with_postlist_get(self):
どのようなエラーが起きてますか？

2021-08-13 15:48 UTC, masaya09 commented on tweet/tests.py
> +class PostUpdateViewTests(TestCase):
UserPassesTestMixinを追加したことで、html上の{% if object.author == user %}は消しました。
したがって、なりすまし時のテストはGET、POST共に403にしました。

2021-08-14 01:34 UTC, Akinori13 commented on tweet/tests.py
> +    def test_with_postlist_get(self):
順序が異なるというエラーが生じます。
２つのツイートは同時に登録されます。場合によっては二つ目のツイートが最初のツイートより先に登録される場合もあります。
主に二つの解決法があります。
`ordered = False`を設定する。
または
```python
import time

self.tweet1 = Post.objects.create~
time.sleep(0.1)
self.tweet2 = Post.objects.create~
```

2021-08-17 13:25 UTC, Akinori13 approved these changes

2021-08-17 13:25 UTC, Akinori13 commented
lgtm

2021-08-18 07:08 UTC, fumiharun11 commented on tweet/models.py
> +    date_posted = models.DateTimeField(default=timezone.now)
第三者視点だと`date_xxx`という命名は`DateField`型の値が格納されているフィールド(カラム)という認識になりやすいので、`DateTimeField`型の値を格納するフィールド名には`xxx_at`という命名をお勧めします。
また、レコードの作成日という意味で捉えて良いと思うので、タイムスタンプ`created_at`という命名でも十分だと思います。
### 参考
https://qiita.com/genzouw/items/35022fa96c120e67c637

2021-08-18 07:08 UTC, fumiharun11 commented on tweet/migrations/0001_initial.py
> +# Generated by Django 3.2.3 on 2021-08-04 14:10
PR単位で更新するmigrationファイルは一つにまとめてください。
今回の場合だと、0001~0003の内容を全て0001に含めて再構成してください。

2021-08-18 07:59 UTC, masaya09 commented on tweet/views.py
> +class MyPostsView(LoginRequiredMixin, ListView):
MyPostListに変更しました

2021-08-18 08:01 UTC, masaya09 commented on tweet/views.py
> +from django.views.generic import DeleteView, ListView
importできました

2021-08-18 08:03 UTC, masaya09 commented on tweet/views.py
> +        return super(PostDeleteView, self).delete(request, *args, **kwargs)
ありません。どちらでもいけたのでどっちがいいのか迷ってました。
とりあえずsuper()の方に統一しました。

2021-08-18 08:57 UTC, fumiharun11 commented on tweet/views.py
> +        context['my_posts_count'] = qs.count()
伝え方が悪かったので追記します。
template内で`{{ my_posts_count }}`の箇所を`{{ post_list.count }}`とすることでquerysetのcountを取得することも可能なので、get_context_dataメソッド内でクエリする必要はないように考えています。
必要以上にクエリすることは避けたいので、上記の記述を個人的にはお勧めします。

2021-08-18 12:27 UTC, fumiharun11 approved these changes
LGTM
![](https://media.giphy.com/media/3o7abB06u9bNzA8lu8/giphy.gif)

2021-08-18 12:27 UTC, merged