フォロー機能の実装
masaya09/TwitterCloneApp pull request #4
Opened 2021-08-24 14:36 UTC by masaya09

フォロー機能を実装しました。　
問題がないか確認よろしくお願いします。

2021-08-29 10:03 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-09-05 02:10 UTC, Akinori13 commented
LGTM

2021-09-05 02:10 UTC, Akinori13 approved these changes

2021-09-07 04:55 UTC, fumiharun11 reviewed
全体的に良いと思います。テストも細かく書けていてGoodです:+1:
コメント箇所の確認をお願いします。

2021-09-07 04:55 UTC, fumiharun11 commented on tweet/views.py
> +        context['follower_count'] = followers.count()
`following_count`と`follower_count`は同じようなクエリが発行される想定だったのだけど、差がある理由を教えてもらえますか？

2021-09-07 04:55 UTC, fumiharun11 commented on accounts/views.py
> +        unfollow = Relationship.objects.filter(follower=follower, following=following)
確認ですが、`Relationship`オブジェクトが存在しない場合もelseの処理に含めている認識で合っていますか？

2021-09-07 04:55 UTC, fumiharun11 commented on accounts/views.py
> +        context['my_posts_count'] = Post.objects.filter(author=self.request.user).count()
`FollowersView`の`get_context_data`メソッドとクエリの発行のされ方が基本的に同じになる認識だったのですが、差がある理由があれば教えてください。

2021-09-07 09:21 UTC, masaya09 commented on tweet/views.py
> +        context['follower_count'] = followers.count()
２通りで試していたのをそのままにしていました。
followers.count()からUser.objects.filter(id__in=followers).count()へと変更しました。

2021-09-07 09:50 UTC, masaya09 commented on accounts/views.py
> +        unfollow = Relationship.objects.filter(follower=follower, following=following)
follower == followingの場合かそれ以外でしか考えていませんでした。

if Relationship.objects.filter(follower=follower, following=following).exists():
        unfollow = Relationship.objects.filter(follower=follower, following=following)
        unfollow.delete()
else:
        messages.warning(request, '無効な操作です')
として、フォローしている時だけフォロー解除できるようにしてみました。

2021-09-07 10:05 UTC, masaya09 commented on accounts/views.py
> +        context['my_posts_count'] = Post.objects.filter(author=self.request.user).count()
followers.html上で、フォロワーをフォローしている場合とフォローしていない場合とに分けるために、FollowersViewにfollowing_listのクエリを追加しました

2021-09-08 05:21 UTC, fumiharun11 approved these changes
![](https://media.tumblr.com/b999d6fa94d40545edb2dac70623e070/tumblr_inline_n2ztfg6zr01qaxsyz.gif)

2021-09-08 05:21 UTC, merged